### ISSUE TITLE
Feature request: Possibility to add option for showing DCC guidance at later stage

### ISSUE THREAD

**Issue by aaikedw** [DMPbelgium/DMPonline_v4#35] opened 2020-08-18 10:13 UTC
Currently it seems that the option to show DCC guidance needs to be clicked when creating the DMP.

![CleanShot 2020-08-18 at 12 08 01](https://user-images.githubusercontent.com/9320501/90500920-d7f25080-e14b-11ea-9bb1-0811281ace4d.png)

As this may become relevant in a later stage/phase in the DMP process it seems interesting to offer the possibility to add this option under "Edit plan details".

**Comment by mm449** [comment] 2020-09-14 12:42
More flexibility to select guidance and switch it on & off (even after creating a plan) is a new feature in DMProadmap, the new version of the software to which we will be upgrading

**Comment by laurastandaert** [comment] 2021-12-14 14:30
Duplicate of #22 
Has been included in update to Roadmap software (sept 2021)

**Closed as completed by laurastandaert** 2021-12-14 14:30 UTC
